### PR TITLE
Major overhaul!

### PR DESCRIPTION
**Pull request by aaronbell**
I realized that the main reason why the font was not building properly was that there was not a complete designspace (thanks to Adam ranting about how different system interpret designspaces!), and 7pt ExtraLight was missing. 

Rather than just try to generate another UFO to stick into the system, I thought it made sense to convert the whole system back to a Glyphs source (handily, the final delivery from the designers is still around), and build via UFR. A couple notes about the outcome:

1) Unfortunately, the rvrn substitutions are more complex than can be handled in Glyphs, so that required custom designspace documents to be able to process them. If we can find a way to integrate the rvrn in more cleanly, this will not be necessary.

2) Until GF can handle a complete FVAR with the full set of Optical Size instances, we have to split the  variable and static instance designspace documents into separate files, further complicating the build process. When this restriction is removed, the files can be merged back.

3) Due to fontmake's way of processing the files, I had to make some modifications to the sources to ensure that things are rendering correctly. These changes are / should be unnoticeable. 

4) Sorry about the VERY LARGE number of changes. I deleted the old UFOs, which accounted for most of that. 

5) Building all the static instances can take a looooooong time. Very long time. FYI.

AFAIK, there are no regressions. Thanks!

### CODE REVIEW

**Comment by aaronbell** [comment]
[literata.zip](https://github.com/googlefonts/literata/files/7268967/literata.zip)
Realized I needed to provide Rosalie with this :)

**Comment by RosaWagner** [comment]
Looks good to me, @m4rc1e can you take a look at this?

**Comment by m4rc1e** [comment]
The GDEF table is wrong. The acute, grave which should have spaces etc have been added as marks when they shouldn't be.

image

**Comment by RosaWagner** [comment]
If this is the only problem we can merge and I'll fix the gdef table. There is a confusion in the source between "comb" accents and legacy naming.

**Comment by RosaWagner** [comment]
made #42 to replace this one. So closing here.

**Pull request closed without merging**
